// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package server

import (
	"context"

	"gyu-oj-backend/app/judge/cmd/rpc/internal/logic"
	"gyu-oj-backend/app/judge/cmd/rpc/internal/svc"
	"gyu-oj-backend/app/judge/cmd/rpc/pb"
)

type JudgeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedJudgeServer
}

func NewJudgeServer(svcCtx *svc.ServiceContext) *JudgeServer {
	return &JudgeServer{
		svcCtx: svcCtx,
	}
}

func (s *JudgeServer) DoJudge(ctx context.Context, in *pb.JudgeReq) (*pb.JudgeResp, error) {
	l := logic.NewDoJudgeLogic(ctx, s.svcCtx)
	return l.DoJudge(in)
}
