// Code generated by goctl. DO NOT EDIT.
// Source: sandbox.proto

package codesandbox

import (
	"context"

	"gyu-oj-backend/app/sandbox/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecuteCodeReq  = pb.ExecuteCodeReq
	ExecuteCodeResp = pb.ExecuteCodeResp

	CodeSandbox interface {
		ExecuteCode(ctx context.Context, in *ExecuteCodeReq, opts ...grpc.CallOption) (*ExecuteCodeResp, error)
	}

	defaultCodeSandbox struct {
		cli zrpc.Client
	}
)

func NewCodeSandbox(cli zrpc.Client) CodeSandbox {
	return &defaultCodeSandbox{
		cli: cli,
	}
}

func (m *defaultCodeSandbox) ExecuteCode(ctx context.Context, in *ExecuteCodeReq, opts ...grpc.CallOption) (*ExecuteCodeResp, error) {
	client := pb.NewCodeSandboxClient(m.cli.Conn())
	return client.ExecuteCode(ctx, in, opts...)
}
