// Code generated by goctl. DO NOT EDIT.
// Source: question.proto

package server

import (
	"context"

	"gyu-oj-backend/app/question/cmd/rpc/internal/logic/questionsubmit"
	"gyu-oj-backend/app/question/cmd/rpc/internal/svc"
	"gyu-oj-backend/app/question/cmd/rpc/pb"
)

type QuestionSubmitServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQuestionSubmitServer
}

func NewQuestionSubmitServer(svcCtx *svc.ServiceContext) *QuestionSubmitServer {
	return &QuestionSubmitServer{
		svcCtx: svcCtx,
	}
}

func (s *QuestionSubmitServer) DoQuestionSubmit(ctx context.Context, in *pb.QuestionSubmitAddReq) (*pb.QuestionSubmitAddResp, error) {
	l := questionsubmitlogic.NewDoQuestionSubmitLogic(ctx, s.svcCtx)
	return l.DoQuestionSubmit(in)
}

func (s *QuestionSubmitServer) QueryQuestionSubmit(ctx context.Context, in *pb.QuestionSubmitListByPageReq) (*pb.QuestionSubmitListByPageResp, error) {
	l := questionsubmitlogic.NewQueryQuestionSubmitLogic(ctx, s.svcCtx)
	return l.QueryQuestionSubmit(in)
}
