// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id         uint64 `json:"id"`
	Username   string `json:"username"`
	Password   string `json:"password"`
	AvatarUrl  string `json:"avatar_url"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	UserRole   uint8  `json:"user_role"`
	IsDelete   uint8  `json:"is_delete"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type RegisterReq struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type RegisterResp struct {
	Username string `json:"username"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id          uint64 `json:"id"`
	Username    string `json:"username"`
	AvatarUrl   string `json:"avatarUrl"`
	UserRole    uint8  `json:"userRole"`
	Token       string `json:"token"`
	TokenExpire int64  `json:"tokenExpire"`
}

type CurrentUserReq struct {
	Authorization string `header:"authorization"`
}

type CurrentUserResp struct {
	Id          uint64 `json:"id"`
	Username    string `json:"username"`
	AvatarUrl   string `json:"avatarUrl"`
	UserRole    uint8  `json:"userRole"`
	Token       string `json:"token"`
	TokenExpire int64  `json:"tokenExpire"`
}

type LogoutReq struct {
	Authorization string `header:"authorization"`
}

type LogoutResp struct {
	IsLogouted bool `json:"isLogouted"`
}
