global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'user-api'
    static_configs:
      - targets: [ 'gyu_oj_service:4001' ]
        labels:
          job: user-api
          app: user-api
          env: dev
  - job_name: 'user-rpc'
    static_configs:
      - targets: [ 'gyu_oj_service:4002' ]
        labels:
          job: user-rpc
          app: user-rpc
          env: dev
  - job_name: 'question-api'
    static_configs:
      - targets: [ 'gyu_oj_service:4003' ]
        labels:
          job: question-api
          app: question-api
          env: dev
  - job_name: 'question-rpc'
    static_configs:
      - targets: [ 'gyu_oj_service:4004' ]
        labels:
          job: question-rpc
          app: question-rpc
          env: dev
  - job_name: 'judge-rpc'
    static_configs:
      - targets: [ 'gyu_oj_service:4005' ]
        labels:
          job: judge-rpc
          app: judge-rpc
          env: dev
  - job_name: 'judge-mq'
    static_configs:
      - targets: [ 'gyu_oj_service:4006' ]
        labels:
          job: judge-mq
          app: judge-mq
          env: dev
  - job_name: 'sandbox-rpc'
    static_configs:
      - targets: ['gyu_oj_service:4007']
        labels:
          job: sandbox-rpc
          app: sandbox-rpc
          env: dev