// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameQuestion = "question"

// Question 题目
type Question struct {
	ID          int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:id" json:"id,string"`                   // id
	Title       string    `gorm:"column:title;type:varchar(512);comment:标题" json:"title"`                                            // 标题
	Content     string    `gorm:"column:content;type:text;comment:内容" json:"content"`                                                // 内容
	Tags        string    `gorm:"column:tags;type:varchar(1024);comment:标签列表（json 数组）" json:"tags"`                                  // 标签列表（json 数组）
	Answer      string    `gorm:"column:answer;type:text;comment:题目答案" json:"answer"`                                                // 题目答案
	SubmitNum   int64     `gorm:"column:submitNum;type:int;not null;comment:题目提交数" json:"submitNum"`                                 // 题目提交数
	AcceptedNum int64     `gorm:"column:acceptedNum;type:int;not null;comment:题目通过数" json:"acceptedNum"`                             // 题目通过数
	JudgeCases  string    `gorm:"column:judgeCases;type:text;comment:判题用例（json 数组）" json:"judgeCases"`                               // 判题用例（json 数组）
	JudgeConfig string    `gorm:"column:judgeConfig;type:text;comment:判题配置（json 对象）" json:"judgeConfig"`                             // 判题配置（json 对象）
	UserID      int64     `gorm:"column:userId;type:bigint;not null;comment:创建用户 id" json:"userId"`                                  // 创建用户 id
	CreateTime  time.Time `gorm:"column:createTime;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime  time.Time `gorm:"column:updateTime;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	IsDelete    int64     `gorm:"column:isDelete;type:tinyint;not null;comment:是否删除" json:"isDelete"`                                // 是否删除
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
